// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service bound to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";

/**
 * AddCredential adds a new API credential.
 * @param {types$0.APICredential} cred
 * @returns {$CancellablePromise<void>}
 */
export function AddCredential(cred) {
    return $Call.ByID(1803223789, cred);
}

/**
 * AddProvider adds a legacy provider by creating credential + profile.
 * Deprecated: Use AddCredential + AddTranslationProfile instead.
 * @param {types$0.Provider} p
 * @returns {$CancellablePromise<void>}
 */
export function AddProvider(p) {
    return $Call.ByID(2250278137, p);
}

/**
 * AddTranslationProfile adds a new translation profile.
 * @param {types$0.TranslationProfile} profile
 * @returns {$CancellablePromise<void>}
 */
export function AddTranslationProfile(profile) {
    return $Call.ByID(1708036840, profile);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<types$0.DetectResult>}
 */
export function DetectLanguage(text) {
    return $Call.ByID(2080537768, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAccessibilityPermission() {
    return $Call.ByID(603609966);
}

/**
 * GetActiveProvider returns the active provider in legacy format.
 * @returns {$CancellablePromise<types$0.Provider | null>}
 */
export function GetActiveProvider() {
    return $Call.ByID(4225032696).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetActiveTranslationProfile returns the currently active translation profile.
 * @returns {$CancellablePromise<types$0.TranslationProfile | null>}
 */
export function GetActiveTranslationProfile() {
    return $Call.ByID(3562388597).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetCredentials returns all API credentials.
 * @returns {$CancellablePromise<types$0.APICredential[]>}
 */
export function GetCredentials() {
    return $Call.ByID(1505250063).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetDefaultLanguages() {
    return $Call.ByID(2348464387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetLiveStatus returns the current live translation status.
 * @returns {$CancellablePromise<types$0.LiveStatus>}
 */
export function GetLiveStatus() {
    return $Call.ByID(1415338303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetProviders returns legacy Provider list for backward compatibility.
 * Deprecated: Use GetTranslationProfiles instead.
 * @returns {$CancellablePromise<types$0.Provider[]>}
 */
export function GetProviders() {
    return $Call.ByID(2525123639).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetScreenRecordingPermission() {
    return $Call.ByID(1250061377);
}

/**
 * GetSpeechConfig returns the speech service configuration.
 * @returns {$CancellablePromise<types$0.SpeechConfig | null>}
 */
export function GetSpeechConfig() {
    return $Call.ByID(1620432715).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetTranslationProfiles returns all translation profiles.
 * @returns {$CancellablePromise<types$0.TranslationProfile[]>}
 */
export function GetTranslationProfiles() {
    return $Call.ByID(1590109544).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * Init initializes the service with references to app and window.
 * @param {application$0.App | null} app
 * @param {application$0.Window} window
 * @returns {$CancellablePromise<void>}
 */
export function Init(app, window) {
    return $Call.ByID(2832927211, app, window);
}

/**
 * RemoveCredential removes a credential by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCredential(id) {
    return $Call.ByID(1745722712, id);
}

/**
 * RemoveProvider removes a legacy provider.
 * Deprecated: Use RemoveTranslationProfile instead.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProvider(name) {
    return $Call.ByID(3305555996, name);
}

/**
 * RemoveTranslationProfile removes a translation profile by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTranslationProfile(id) {
    return $Call.ByID(2228403001, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RequestScreenRecordingPermission() {
    return $Call.ByID(3897512642);
}

/**
 * @param {string} src
 * @param {string} dst
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultLanguage(src, dst) {
    return $Call.ByID(4015847990, src, dst);
}

/**
 * SetProviderActive sets a legacy provider as active.
 * Deprecated: Use SetTranslationProfileActive instead.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetProviderActive(name) {
    return $Call.ByID(2658953724, name);
}

/**
 * SetSpeechConfig sets the speech service configuration.
 * @param {types$0.SpeechConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetSpeechConfig(cfg) {
    return $Call.ByID(2863537943, cfg);
}

/**
 * SetTranslationProfileActive sets a translation profile as active.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetTranslationProfileActive(id) {
    return $Call.ByID(3105372105, id);
}

/**
 * Shutdown cleans up resources.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2987688963);
}

/**
 * StartAudioCapture starts capturing system audio and streams it to frontend.
 * Audio samples are emitted as "audio-samples" events.
 * @returns {$CancellablePromise<void>}
 */
export function StartAudioCapture() {
    return $Call.ByID(189350683);
}

/**
 * StartLiveTranslation starts real-time audio translation.
 * Uses factory pattern - main.go doesn't need to know implementation details.
 * @param {string} sourceLang
 * @param {string} targetLang
 * @returns {$CancellablePromise<void>}
 */
export function StartLiveTranslation(sourceLang, targetLang) {
    return $Call.ByID(635984740, sourceLang, targetLang);
}

/**
 * StopAudioCapture stops the audio capture.
 * @returns {$CancellablePromise<void>}
 */
export function StopAudioCapture() {
    return $Call.ByID(231236605);
}

/**
 * StopLiveTranslation stops real-time audio translation.
 * @returns {$CancellablePromise<void>}
 */
export function StopLiveTranslation() {
    return $Call.ByID(161307806);
}

/**
 * TakeScreenshotAndOCR captures a screenshot and performs OCR.
 * Returns the recognized text.
 * @returns {$CancellablePromise<string>}
 */
export function TakeScreenshotAndOCR() {
    return $Call.ByID(4282498237);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleWindowVisibility() {
    return $Call.ByID(2241336245);
}

/**
 * @param {types$0.TranslateRequest} req
 * @returns {$CancellablePromise<types$0.TranslateResult>}
 */
export function TranslateWithLLM(req) {
    return $Call.ByID(2352175956, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * UpdateCredential updates an existing credential.
 * @param {string} id
 * @param {types$0.APICredential} cred
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCredential(id, cred) {
    return $Call.ByID(2832677181, id, cred);
}

/**
 * UpdateProvider updates a legacy provider.
 * Deprecated: Use UpdateTranslationProfile instead.
 * @param {string} name
 * @param {types$0.Provider} p
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProvider(name, p) {
    return $Call.ByID(995769993, name, p);
}

/**
 * UpdateTranslationProfile updates an existing translation profile.
 * @param {string} id
 * @param {types$0.TranslationProfile} profile
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTranslationProfile(id, profile) {
    return $Call.ByID(2126047032, id, profile);
}

// Private type creation functions
const $$createType0 = types$0.DetectResult.createFrom;
const $$createType1 = types$0.Provider.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = types$0.TranslationProfile.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = types$0.APICredential.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = types$0.LiveStatus.createFrom;
const $$createType9 = $Create.Array($$createType1);
const $$createType10 = types$0.SpeechConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType3);
const $$createType13 = types$0.TranslateResult.createFrom;
