// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service bound to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./internal/types/models.js";

/**
 * @param {types$0.Provider} p
 * @returns {$CancellablePromise<void>}
 */
export function AddProvider(p) {
    return $Call.ByID(2250278137, p);
}

/**
 * @param {string} text
 * @returns {$CancellablePromise<types$0.DetectResult>}
 */
export function DetectLanguage(text) {
    return $Call.ByID(2080537768, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAccessibilityPermission() {
    return $Call.ByID(603609966);
}

/**
 * @returns {$CancellablePromise<types$0.Provider | null>}
 */
export function GetActiveProvider() {
    return $Call.ByID(4225032696).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetDefaultLanguages() {
    return $Call.ByID(2348464387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetLiveStatus returns the current live translation status.
 * @returns {$CancellablePromise<types$0.LiveStatus>}
 */
export function GetLiveStatus() {
    return $Call.ByID(1415338303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.Provider[]>}
 */
export function GetProviders() {
    return $Call.ByID(2525123639).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSTTProviders returns available STT providers.
 * @returns {$CancellablePromise<types$0.STTProviderInfo[]>}
 */
export function GetSTTProviders() {
    return $Call.ByID(4069245102).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSTTSetupProgress returns the setup progress for a provider.
 * @param {string} name
 * @returns {$CancellablePromise<number>}
 */
export function GetSTTSetupProgress(name) {
    return $Call.ByID(3416966226, name);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function GetScreenRecordingPermission() {
    return $Call.ByID(1250061377);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * Init initializes the service with references to app and window.
 * @param {application$0.App | null} app
 * @param {application$0.Window} window
 * @returns {$CancellablePromise<void>}
 */
export function Init(app, window) {
    return $Call.ByID(2832927211, app, window);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProvider(name) {
    return $Call.ByID(3305555996, name);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RequestScreenRecordingPermission() {
    return $Call.ByID(3897512642);
}

/**
 * @param {string} src
 * @param {string} dst
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultLanguage(src, dst) {
    return $Call.ByID(4015847990, src, dst);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetProviderActive(name) {
    return $Call.ByID(2658953724, name);
}

/**
 * SetSTTProvider sets the active STT provider for live translation.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetSTTProvider(name) {
    return $Call.ByID(485975085, name);
}

/**
 * SetupSTTProvider downloads/initializes an STT provider.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function SetupSTTProvider(name) {
    return $Call.ByID(109836374, name);
}

/**
 * Shutdown cleans up resources.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(2987688963);
}

/**
 * StartLiveTranslation starts real-time audio translation.
 * @param {string} sourceLang
 * @param {string} targetLang
 * @returns {$CancellablePromise<void>}
 */
export function StartLiveTranslation(sourceLang, targetLang) {
    return $Call.ByID(635984740, sourceLang, targetLang);
}

/**
 * StopLiveTranslation stops real-time audio translation.
 * @returns {$CancellablePromise<void>}
 */
export function StopLiveTranslation() {
    return $Call.ByID(161307806);
}

/**
 * TakeScreenshotAndOCR captures a screenshot and performs OCR.
 * Returns the recognized text.
 * @returns {$CancellablePromise<string>}
 */
export function TakeScreenshotAndOCR() {
    return $Call.ByID(4282498237);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleWindowVisibility() {
    return $Call.ByID(2241336245);
}

/**
 * @param {types$0.TranslateRequest} req
 * @returns {$CancellablePromise<types$0.TranslateResult>}
 */
export function TranslateWithLLM(req) {
    return $Call.ByID(2352175956, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} name
 * @param {types$0.Provider} p
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProvider(name, p) {
    return $Call.ByID(995769993, name, p);
}

// Private type creation functions
const $$createType0 = types$0.DetectResult.createFrom;
const $$createType1 = types$0.Provider.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = types$0.LiveStatus.createFrom;
const $$createType5 = $Create.Array($$createType1);
const $$createType6 = types$0.STTProviderInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = types$0.TranslateResult.createFrom;
