// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides application functionality bound to Wails.
 * This struct focuses on orchestration; business logic lives in sub-components.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * AddCredential adds a new API credential.
 * @param {types$0.APICredential} cred
 * @returns {$CancellablePromise<void>}
 */
export function AddCredential(cred) {
    return $Call.ByID(3013189672, cred);
}

/**
 * AddTranslationProfile adds a new translation profile.
 * @param {types$0.TranslationProfile} profile
 * @returns {$CancellablePromise<void>}
 */
export function AddTranslationProfile(profile) {
    return $Call.ByID(2849441481, profile);
}

/**
 * DetectLanguage detects the language of the given text.
 * @param {string} text
 * @returns {$CancellablePromise<types$0.DetectResult>}
 */
export function DetectLanguage(text) {
    return $Call.ByID(4253480727, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAccessibilityPermission returns whether accessibility is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAccessibilityPermission() {
    return $Call.ByID(3193766237);
}

/**
 * GetActiveTranslationProfile returns the currently active translation profile.
 * @returns {$CancellablePromise<types$0.TranslationProfile | null>}
 */
export function GetActiveTranslationProfile() {
    return $Call.ByID(1552550560).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCredentials returns all API credentials.
 * @returns {$CancellablePromise<types$0.APICredential[]>}
 */
export function GetCredentials() {
    return $Call.ByID(2468432036).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetDefaultLanguages returns the default language mappings.
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetDefaultLanguages() {
    return $Call.ByID(2984789062).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetLiveStatus returns the current live translation status.
 * @returns {$CancellablePromise<types$0.LiveStatus>}
 */
export function GetLiveStatus() {
    return $Call.ByID(967279082).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetScreenRecordingPermission returns whether screen recording is permitted.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetScreenRecordingPermission() {
    return $Call.ByID(1167194682);
}

/**
 * GetSpeechConfig returns the speech service configuration.
 * @returns {$CancellablePromise<types$0.SpeechConfig | null>}
 */
export function GetSpeechConfig() {
    return $Call.ByID(1090795462).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetTranslationProfiles returns all translation profiles.
 * @returns {$CancellablePromise<types$0.TranslationProfile[]>}
 */
export function GetTranslationProfiles() {
    return $Call.ByID(1041603327).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetVersion returns the application version.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(3918139534);
}

/**
 * Init initializes the service with app and window references.
 * Must be called after Wails application is created.
 * @param {application$0.App | null} app
 * @param {application$0.Window} window
 * @returns {$CancellablePromise<void>}
 */
export function Init(app, window) {
    return $Call.ByID(1531681436, app, window);
}

/**
 * RemoveCredential removes a credential by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCredential(id) {
    return $Call.ByID(2781249375, id);
}

/**
 * RemoveTranslationProfile removes a translation profile by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTranslationProfile(id) {
    return $Call.ByID(3915708534, id);
}

/**
 * RequestScreenRecordingPermission requests screen recording permission.
 * @returns {$CancellablePromise<void>}
 */
export function RequestScreenRecordingPermission() {
    return $Call.ByID(3547072165);
}

/**
 * SetDefaultLanguage sets the default target language for a source.
 * @param {string} src
 * @param {string} dst
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultLanguage(src, dst) {
    return $Call.ByID(4047059509, src, dst);
}

/**
 * SetSpeechConfig sets the speech service configuration.
 * @param {types$0.SpeechConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SetSpeechConfig(cfg) {
    return $Call.ByID(3817527442, cfg);
}

/**
 * SetTranslationProfileActive sets a translation profile as active.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetTranslationProfileActive(id) {
    return $Call.ByID(2928798996, id);
}

/**
 * SetupSystemTray configures the system tray menu.
 * Must be called after Init.
 * @param {string} icon
 * @returns {$CancellablePromise<void>}
 */
export function SetupSystemTray(icon) {
    return $Call.ByID(2145896726, icon);
}

/**
 * Shutdown cleans up resources.
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1599179000);
}

/**
 * StartLiveTranslation starts real-time audio translation.
 * @param {string} sourceLang
 * @param {string} targetLang
 * @returns {$CancellablePromise<void>}
 */
export function StartLiveTranslation(sourceLang, targetLang) {
    return $Call.ByID(2362686847, sourceLang, targetLang);
}

/**
 * StopLiveTranslation stops real-time audio translation.
 * @returns {$CancellablePromise<void>}
 */
export function StopLiveTranslation() {
    return $Call.ByID(1785532871);
}

/**
 * TakeScreenshotAndOCR captures a screenshot and performs OCR.
 * @returns {$CancellablePromise<string>}
 */
export function TakeScreenshotAndOCR() {
    return $Call.ByID(3946336602);
}

/**
 * ToggleWindowVisibility shows the window with clipboard text.
 * @returns {$CancellablePromise<void>}
 */
export function ToggleWindowVisibility() {
    return $Call.ByID(3590709818);
}

/**
 * TranslateWithLLM translates text using the active provider.
 * @param {types$0.TranslateRequest} req
 * @returns {$CancellablePromise<types$0.TranslateResult>}
 */
export function TranslateWithLLM(req) {
    return $Call.ByID(4038648379, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * TranslateWithLLMStream translates text with streaming output via events.
 * @param {types$0.TranslateRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function TranslateWithLLMStream(req) {
    return $Call.ByID(2490205331, req);
}

/**
 * UpdateCredential updates an existing credential.
 * @param {string} id
 * @param {types$0.APICredential} cred
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCredential(id, cred) {
    return $Call.ByID(2844507110, id, cred);
}

/**
 * UpdateTranslationProfile updates an existing translation profile.
 * @param {string} id
 * @param {types$0.TranslationProfile} profile
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTranslationProfile(id, profile) {
    return $Call.ByID(1532085003, id, profile);
}

// Private type creation functions
const $$createType0 = types$0.DetectResult.createFrom;
const $$createType1 = types$0.TranslationProfile.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = types$0.APICredential.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = types$0.LiveStatus.createFrom;
const $$createType7 = types$0.SpeechConfig.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType1);
const $$createType10 = types$0.TranslateResult.createFrom;
