// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    APICredential,
    DetectResult,
    LiveStatus,
    Provider,
    SpeechConfig,
    TranslateRequest,
    TranslateResult,
    TranslationProfile,
    Usage,
    VADState
} from "./models.js";
