// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * APICredential represents a reusable API credential.
 * One credential can be used by multiple translation profiles or speech services.
 */
export class APICredential {
    /**
     * Creates a new APICredential instance.
     * @param {Partial<APICredential>} [$$source = {}] - The source object to create the APICredential.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * UUID for reference
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * Display name, e.g., "My OpenAI"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "openai", "openai-compatible", "gemini", "claude"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Custom endpoint (required for openai-compatible)
             * @member
             * @type {string | undefined}
             */
            this["base_url"] = undefined;
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new APICredential instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {APICredential}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new APICredential(/** @type {Partial<APICredential>} */($$parsedSource));
    }
}

/**
 * DetectResult represents the result of language detection.
 */
export class DetectResult {
    /**
     * Creates a new DetectResult instance.
     * @param {Partial<DetectResult>} [$$source = {}] - The source object to create the DetectResult.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("defaultTarget" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultTarget"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectResult(/** @type {Partial<DetectResult>} */($$parsedSource));
    }
}

/**
 * LiveStatus represents the status of live translation.
 */
export class LiveStatus {
    /**
     * Creates a new LiveStatus instance.
     * @param {Partial<LiveStatus>} [$$source = {}] - The source object to create the LiveStatus.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("sourceLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceLang"] = "";
        }
        if (!("targetLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetLang"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * Running duration in seconds
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("sttProvider" in $$source)) {
            /**
             * Current STT provider name
             * @member
             * @type {string}
             */
            this["sttProvider"] = "";
        }
        if (!("transcriptCount" in $$source)) {
            /**
             * Number of transcribed segments
             * @member
             * @type {number}
             */
            this["transcriptCount"] = 0;
        }
        if (!("vadState" in $$source)) {
            /**
             * Current VAD state
             * @member
             * @type {VADState}
             */
            this["vadState"] = VADState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveStatus(/** @type {Partial<LiveStatus>} */($$parsedSource));
    }
}

/**
 * SpeechConfig represents speech service configuration (STT, speech translation, etc).
 * Requires an OpenAI-compatible API credential.
 */
export class SpeechConfig {
    /**
     * Creates a new SpeechConfig instance.
     * @param {Partial<SpeechConfig>} [$$source = {}] - The source object to create the SpeechConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * Whether speech API is enabled
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("credential_id" in $$source)) {
            /**
             * Reference to APICredential.ID
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * e.g., "whisper-1" or "gpt-4o-realtime-preview"
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * "transcription" (default) or "realtime"
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpeechConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SpeechConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpeechConfig(/** @type {Partial<SpeechConfig>} */($$parsedSource));
    }
}

/**
 * TranslateRequest represents a translation request from the frontend.
 */
export class TranslateRequest {
    /**
     * Creates a new TranslateRequest instance.
     * @param {Partial<TranslateRequest>} [$$source = {}] - The source object to create the TranslateRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("sourceLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceLang"] = "";
        }
        if (!("targetLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetLang"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Previous context for better coherence
             * @member
             * @type {string | undefined}
             */
            this["context"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslateRequest(/** @type {Partial<TranslateRequest>} */($$parsedSource));
    }
}

/**
 * TranslateResult represents the result of a translation request.
 */
export class TranslateResult {
    /**
     * Creates a new TranslateResult instance.
     * @param {Partial<TranslateResult>} [$$source = {}] - The source object to create the TranslateResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["usage"] = (new Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        return new TranslateResult(/** @type {Partial<TranslateResult>} */($$parsedSource));
    }
}

/**
 * TranslationProfile represents a translation configuration bound to an API credential.
 */
export class TranslationProfile {
    /**
     * Creates a new TranslationProfile instance.
     * @param {Partial<TranslationProfile>} [$$source = {}] - The source object to create the TranslationProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * UUID
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * Display name
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("credential_id" in $$source)) {
            /**
             * Reference to APICredential.ID
             * @member
             * @type {string}
             */
            this["credential_id"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * Model to use
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["system_prompt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["max_tokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["temperature"] = undefined;
        }
        if (!("active" in $$source)) {
            /**
             * Currently active profile
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["disable_thinking"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslationProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationProfile(/** @type {Partial<TranslationProfile>} */($$parsedSource));
    }
}

/**
 * Usage represents token usage statistics from LLM API calls.
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("promptTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }
        if (!("cacheHit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cacheHit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

/**
 * VADState represents the current voice activity state.
 * @readonly
 * @enum {string}
 */
export const VADState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    VADStateListening: "listening",
    VADStateSpeaking: "speaking",
    VADStateProcessing: "processing",
};

// Private type creation functions
const $$createType0 = Usage.createFrom;
