// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DetectResult represents the result of language detection.
 */
export class DetectResult {
    /**
     * Creates a new DetectResult instance.
     * @param {Partial<DetectResult>} [$$source = {}] - The source object to create the DetectResult.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("defaultTarget" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultTarget"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetectResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetectResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetectResult(/** @type {Partial<DetectResult>} */($$parsedSource));
    }
}

/**
 * Provider represents an LLM provider configuration.
 */
export class Provider {
    /**
     * Creates a new Provider instance.
     * @param {Partial<Provider>} [$$source = {}] - The source object to create the Provider.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "openai", "openai-compatible", "gemini", "claude"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["base_url"] = undefined;
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["system_prompt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["max_tokens"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["temperature"] = undefined;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * For Gemini: set thinkingBudget to 0
             * @member
             * @type {boolean | undefined}
             */
            this["disable_thinking"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Provider}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Provider(/** @type {Partial<Provider>} */($$parsedSource));
    }
}

/**
 * TranslateRequest represents a translation request from the frontend.
 */
export class TranslateRequest {
    /**
     * Creates a new TranslateRequest instance.
     * @param {Partial<TranslateRequest>} [$$source = {}] - The source object to create the TranslateRequest.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("sourceLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceLang"] = "";
        }
        if (!("targetLang" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetLang"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslateRequest(/** @type {Partial<TranslateRequest>} */($$parsedSource));
    }
}

/**
 * TranslateResult represents the result of a translation request.
 */
export class TranslateResult {
    /**
     * Creates a new TranslateResult instance.
     * @param {Partial<TranslateResult>} [$$source = {}] - The source object to create the TranslateResult.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["usage"] = (new Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TranslateResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        return new TranslateResult(/** @type {Partial<TranslateResult>} */($$parsedSource));
    }
}

/**
 * Usage represents token usage statistics from LLM API calls.
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("promptTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }
        if (!("cacheHit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cacheHit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Usage.createFrom;
